[features]
seeds = false
skip-lint = false
[workspace]
members = [
  "programs/pda",
  "programs/hacker",
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/minhdo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
